services:

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: launchstore_db
    ports:
      - 5432:5432
    volumes:
      - ./.docker:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network: